# Generated by Django 3.2.16 on 2023-01-21 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.AutoField(default=uuid.UUID('90a7e17a-eeda-439a-9725-7f54a7a3367e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=models.AutoField(default=uuid.UUID('80d86c7d-60d0-49ed-9e94-1282ee7cf870'), editable=False, primary_key=True, serialize=False),
        ),
    ]
