# Generated by Django 3.2.18 on 2023-03-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
