# Generated by Django 3.2.16 on 2023-01-21 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230121_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numReviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.AutoField(default=uuid.UUID('eb178ced-44a8-4e62-b5cc-6c319cc9d9a5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=models.AutoField(default=uuid.UUID('8d954858-1e31-44f9-a578-1b49acd0958e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
