# Generated by Django 3.2.16 on 2023-01-13 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('11754e19-3423-46d0-8699-a722e35020b0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
