# Generated by Django 3.2.16 on 2023-01-29 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230121_1529'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='order',
        #     name='_id',
        #     field=models.UUIDField(db_index=True, default=uuid.UUID('083d2834-09fd-424b-82ff-809acb769c7b'), editable=False, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='product',
        #     name='_id',
        #     field=models.UUIDField(db_index=True, default=uuid.UUID('4c06018c-55b2-4034-9b0f-f066775c6406'), editable=False, primary_key=True, serialize=False),
        # ),
    ]
