# Generated by Django 3.2.16 on 2023-01-13 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230113_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('d2698799-41b3-498e-a56b-f0c988d15d06'), editable=False, primary_key=True, serialize=False),
        ),
    ]
