# Generated by Django 3.2.16 on 2023-01-29 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230129_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_id',
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('9fa5a6d8-62ef-4cb1-b8db-cb32d1b5657a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('ac75722b-bf6d-467a-b5ba-10b5e05a24e4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
