# Generated by Django 3.2.16 on 2023-01-13 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230113_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('2f13c269-686f-4e9d-ae5f-c632fee15b2c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
