# Generated by Django 3.2.16 on 2023-01-13 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('2b2ecb83-9674-435b-9820-58320ffe51de'), editable=False, primary_key=True, serialize=False),
        ),
    ]
