# Generated by Django 3.2.18 on 2023-04-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230417_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='customer',
        ),
    ]
