# Generated by Django 3.2.18 on 2023-04-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_email_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='order_email',
        ),
    ]
