# Generated by Django 3.2.16 on 2023-01-13 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('070f925d-ced2-4ccc-8142-0b74d5be704d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
