# Generated by Django 3.2.18 on 2023-04-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_customer_order_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_email',
            new_name='customer',
        ),
    ]
