# Generated by Django 3.2.18 on 2023-04-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230419_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.order'),
        ),
    ]
