# Generated by Django 3.2.18 on 2023-04-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_useraccount_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order'),
        ),
    ]
